CREATE TABLE IF NOT EXISTS posts (
	creator_id INTEGER NOT NULL REFERENCES creators(id),
	id INTEGER BIGINT KEY NOT NULL,
	title TEXT NOT NULL,
	post_time TIMESTAMP,
	body TEXT NOT NULL,
	added TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS files(
	post_id BIGINT NOT NULL REFERENCES posts(id),
	typeof INTEGER NOT NULL,
	file_url TEXT NOT NULL,
	added TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	downloaded TIMESTAMP,
	tries INTEGER NOT NULL DEFAULT 0,
	sha256 TEXT,
	UNIQUE (post_id, typeof, file_url)
);
